apiVersion: v1
kind: Namespace
metadata:
  name: graphmind
  labels:
    name: graphmind
    app.kubernetes.io/name: graphmind
    app.kubernetes.io/part-of: distributed-gnn
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: graphmind-quota
  namespace: graphmind
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 200Gi
    requests.nvidia.com/gpu: "10"
    limits.cpu: "100"
    limits.memory: 400Gi
    limits.nvidia.com/gpu: "10"
    persistentvolumeclaims: "20"
    services: "10"
    secrets: "50"
    configmaps: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: graphmind-limits
  namespace: graphmind
spec:
  limits:
  - default:
      cpu: "2"
      memory: 8Gi
      nvidia.com/gpu: "1"
    defaultRequest:
      cpu: "500m"
      memory: 2Gi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim